; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Sep 16 2021 16:40:05 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAEAHRL3E0CI:
	dc.w DATAEAHRL3E0CI_0-DATAEAHRL3E0CI, DATAEAHRL3E0CI_1-DATAEAHRL3E0CI
	dc.w DATAEAHRL3E0CI_2-DATAEAHRL3E0CI, DATAEAHRL3E0CI_3-DATAEAHRL3E0CI
	dc.w DATAEAHRL3E0CI_4-DATAEAHRL3E0CI, DATAEAHRL3E0CI_5-DATAEAHRL3E0CI
DATAEAHRL3E0CI_0: dc.b $2
	dc.b $EF, $9, $0, $0, $F4
	dc.b $FF, $A, $0, $6, $F4
DATAEAHRL3E0CI_1: dc.b $2
	dc.b $EF, $9, $0, $0, $F4
	dc.b $FF, $A, $0, $F, $F4
DATAEAHRL3E0CI_2: dc.b $2
	dc.b $F4, $9, $0, $0, $F4
	dc.b $4, $9, $0, $18, $F4
DATAEAHRL3E0CI_3: dc.b $2
	dc.b $E4, $9, $0, $0, $F4
	dc.b $F4, $A, $0, $1E, $F4
DATAEAHRL3E0CI_4: dc.b $1
	dc.b $F8, $5, $0, $27, $F8
DATAEAHRL3E0CI_5: dc.b $1
	dc.b $F8, $5, $0, $2B, $F8
	even