; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Sep 16 2021 17:18:34 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA6C5OHG5JNPR:
	dc.w DATA6C5OHG5JNPR_0-DATA6C5OHG5JNPR, DATA6C5OHG5JNPR_1-DATA6C5OHG5JNPR
	dc.w DATA6C5OHG5JNPR_2-DATA6C5OHG5JNPR, DATA6C5OHG5JNPR_3-DATA6C5OHG5JNPR
	dc.w DATA6C5OHG5JNPR_4-DATA6C5OHG5JNPR, DATA6C5OHG5JNPR_5-DATA6C5OHG5JNPR
	dc.w DATA6C5OHG5JNPR_6-DATA6C5OHG5JNPR
DATA6C5OHG5JNPR_0: dc.b $4
	dc.b $F0, $9, $0, $0, $E8
	dc.b $F0, $9, $8, $0, $0
	dc.b $0, $5, $0, $6, $F0
	dc.b $0, $5, $8, $6, $0
DATA6C5OHG5JNPR_1: dc.b $4
	dc.b $F0, $9, $0, $A, $E8
	dc.b $F0, $9, $0, $10, $0
	dc.b $0, $5, $0, $16, $F0
	dc.b $0, $9, $0, $1A, $0
DATA6C5OHG5JNPR_2: dc.b $4
	dc.b $EC, $9, $0, $0, $E8
	dc.b $EC, $9, $8, $0, $0
	dc.b $FC, $5, $8, $6, $0
	dc.b $FC, $6, $0, $20, $F0
DATA6C5OHG5JNPR_3: dc.b $4
	dc.b $EC, $9, $0, $A, $E8
	dc.b $EC, $9, $0, $10, $0
	dc.b $FC, $9, $0, $26, $0
	dc.b $FC, $6, $0, $2C, $F0
DATA6C5OHG5JNPR_4: dc.b $6
	dc.b $F0, $4, $0, $32, $F0
	dc.b $F0, $4, $8, $32, $0
	dc.b $F8, $9, $0, $34, $E8
	dc.b $F8, $9, $8, $34, $0
	dc.b $8, $4, $0, $3A, $F0
	dc.b $8, $4, $8, $3A, $0
DATA6C5OHG5JNPR_5: dc.b $1
	dc.b $F8, $5, $0, $3C, $F8
DATA6C5OHG5JNPR_6: dc.b $1
	dc.b $F8, $5, $0, $40, $F8
	even