; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Sep 15 2021 22:08:58 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAHGAC93NRKY:
	dc.w DATAHGAC93NRKY_0-DATAHGAC93NRKY, DATAHGAC93NRKY_1-DATAHGAC93NRKY
	dc.w DATAHGAC93NRKY_2-DATAHGAC93NRKY, DATAHGAC93NRKY_3-DATAHGAC93NRKY
	dc.w DATAHGAC93NRKY_4-DATAHGAC93NRKY
DATAHGAC93NRKY_0: dc.b $2
	dc.b $DE, $E, $0, $0, $F0
	dc.b $F6, $E, $0, $C, $F0
DATAHGAC93NRKY_1: dc.b $2
	dc.b $E6, $E, $0, $0, $F0
	dc.b $FE, $D, $0, $18, $F0
DATAHGAC93NRKY_2: dc.b $1
	dc.b $F0, $F, $0, $20, $F0
DATAHGAC93NRKY_3: dc.b $1
	dc.b $F0, $F, $0, $30, $F0
DATAHGAC93NRKY_4: dc.b $1
	dc.b $F0, $F, $0, $40, $F0
	even